# Generated by Django 4.1.7 on 2023-03-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datasetModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataset', models.FileField(upload_to='media/dataset/')),
                ('filesize', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Upload Dataset',
            },
        ),
    ]
