# Generated by Django 4.1.7 on 2023-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_datasetmodel_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetmodel',
            name='file_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
