# Generated by Django 4.1.7 on 2023-04-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_datasetmodel_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='ad_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='ad_algo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='ad_f1_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='ad_precision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='ad_recall',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='lr_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='lr_algo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='lr_f1_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='lr_precision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='lr_recall',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='xg_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='xg_algo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='xg_f1_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='xg_precision',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='xg_recall',
            field=models.FloatField(null=True),
        ),
    ]
