# Generated by Django 4.1.7 on 2023-04-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_datasetmodel_ad_accuracy_datasetmodel_ad_algo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetmodel',
            name='file_size',
        ),
    ]
