# Generated by Django 4.1.7 on 2023-04-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_predict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Predict',
        ),
    ]
