# Generated by Django 4.1.7 on 2023-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='newbalanceDest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='predict',
            name='newbalanceOrig',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='predict',
            name='oldbalanceDest',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='predict',
            name='oldbalanceOrg',
            field=models.FloatField(null=True),
        ),
    ]
