# Generated by Django 4.1.7 on 2023-04-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_predict_newbalancedest_predict_newbalanceorig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='id',
            new_name='predict_id',
        ),
    ]
