# Generated by Django 4.1.7 on 2023-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_rename_id_predict_predict_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
